server:
  port: 8762

spring:
  application:
    name: SERVICE-REGISTRY

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8762/eureka/
    instance:
      hostname: localhost
  server:
    register-with-eureka: false
    fetch-registry: false